'use client';

import { Inter } from "next/font/google";

import React, { useState, useEffect, useRef } from 'react';
import Head from 'next/head';
import { useParams, useRouter } from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  const router = useRouter();

  return (
    <html lang="en">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body className={`${inter.className} v-flex`}>
        {children}
      </body>
    </html>
  );
}
